// <auto-generated />
using System;
using DgtWebAPI2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DgtWebAPI2.Migrations
{
    [DbContext(typeof(APIDBContext))]
    partial class APIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DgtWebApi2.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actions");

                    b.Property<DateTime?>("ActionsDate");

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime?>("CloseDate");

                    b.Property<bool>("Closed");

                    b.Property<DateTime?>("ComplaintDate")
                        .IsRequired();

                    b.Property<int>("ComplaintTypeId");

                    b.Property<string>("Details")
                        .IsRequired();

                    b.Property<string>("EmailUser")
                        .IsRequired();

                    b.Property<string>("PhoneUser");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintTypeId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("DgtWebApi2.Models.ComplaintType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ComplaintTypes");
                });

            modelBuilder.Entity("DgtWebApi2.Models.Complaint", b =>
                {
                    b.HasOne("DgtWebApi2.Models.ComplaintType", "ComplaintType")
                        .WithMany("Denuncias")
                        .HasForeignKey("ComplaintTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
